### PR TITLE
Ugoiloh

### PR DESCRIPTION
**Pull request by ugoiloh**
Hey guys,

As agreed in our meeting, here's my EDA. Kindly review and comment.

Thanks

### CODE REVIEW

**Review by Chidikay909 — COMMENTED** [review]
This is really exploratory, I think it should be merged.

**Comment by ugoiloh** [comment]
I have made some update on the file and committed it with the message - an updated EDA.

**Review by Abuton — COMMENTED** [review]
Very Nice Work

**Comment by Chrys97** [comment]
Absolutely amazing work

**Pull request merged**
