### PR TITLE
This is an exploratory analysis and visualization of the dataset

### PR DESCRIPTION
**Pull request by Chidikay909**
[Task: Data Wrangling](https://github.com/HamoyeHQ/stage-f-14-house-pricing/projects/1#card-48035051)

### CODE REVIEW

**Comment by Chidikay909** [comment]
As agreed in our meeting, I have created an exploratory Data Analysis for the dataset.

**Review by Abuton — COMMENTED** [review]
Amazing work

**Comment by ugoiloh** [comment]
Well done @Chidikay909!

Great efforts on coming up with this.

**Comment by qudus-ade** [comment]
What an outstanding work

**Comment by damisotomi** [comment]
Great work

**Pull request merged**
